javac StringTest01.java
touch st.txt | javap -verbose StringTest01 > st.txt
javap -verbose StringTest01

Classfile /Users/cl/ideaProjects/kiibos-micoservice/kiibos_8_jvm/src/main/java/com/kiibos/micoservice/kiibos_8_jvm/stringIntern/StringTest01.class
  Last modified 2019-3-5; size 1076 bytes
  MD5 checksum 0cee37ad98faa53102f19182efaf2720
  Compiled from "StringTest01.java"
public class com.kiibos.micoservice.kiibos_8_jvm.stringIntern.StringTest01
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Methodref          #15.#28        // java/lang/Object."<init>":()V
   #2 = String             #29            // baseStr
   #3 = String             #30            // baseStr01
   #4 = Class              #31            // java/lang/StringBuilder
   #5 = Methodref          #4.#28         // java/lang/StringBuilder."<init>":()V
   #6 = Methodref          #4.#32         // java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
   #7 = String             #33            // 01
   #8 = Methodref          #4.#34         // java/lang/StringBuilder.toString:()Ljava/lang/String;
   #9 = Class              #35            // java/lang/String
  #10 = Methodref          #9.#36         // java/lang/String."<init>":(Ljava/lang/String;)V
  #11 = Methodref          #9.#37         // java/lang/String.intern:()Ljava/lang/String;
  #12 = Fieldref           #38.#39        // java/lang/System.out:Ljava/io/PrintStream;
  #13 = Methodref          #40.#41        // java/io/PrintStream.println:(Z)V
  #14 = Class              #42            // com/kiibos/micoservice/kiibos_8_jvm/stringIntern/StringTest01
  #15 = Class              #43            // java/lang/Object
  #16 = Utf8               <init>
  #17 = Utf8               ()V
  #18 = Utf8               Code
  #19 = Utf8               LineNumberTable
  #20 = Utf8               main
  #21 = Utf8               ([Ljava/lang/String;)V
  #22 = Utf8               StackMapTable
  #23 = Class              #44            // "[Ljava/lang/String;"
  #24 = Class              #35            // java/lang/String
  #25 = Class              #45            // java/io/PrintStream
  #26 = Utf8               SourceFile
  #27 = Utf8               StringTest01.java
  #28 = NameAndType        #16:#17        // "<init>":()V
  #29 = Utf8               baseStr
  #30 = Utf8               baseStr01
  #31 = Utf8               java/lang/StringBuilder
  #32 = NameAndType        #46:#47        // append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #33 = Utf8               01
  #34 = NameAndType        #48:#49        // toString:()Ljava/lang/String;
  #35 = Utf8               java/lang/String
  #36 = NameAndType        #16:#50        // "<init>":(Ljava/lang/String;)V
  #37 = NameAndType        #51:#49        // intern:()Ljava/lang/String;
  #38 = Class              #52            // java/lang/System
  #39 = NameAndType        #53:#54        // out:Ljava/io/PrintStream;
  #40 = Class              #45            // java/io/PrintStream
  #41 = NameAndType        #55:#56        // println:(Z)V
  #42 = Utf8               com/kiibos/micoservice/kiibos_8_jvm/stringIntern/StringTest01
  #43 = Utf8               java/lang/Object
  #44 = Utf8               [Ljava/lang/String;
  #45 = Utf8               java/io/PrintStream
  #46 = Utf8               append
  #47 = Utf8               (Ljava/lang/String;)Ljava/lang/StringBuilder;
  #48 = Utf8               toString
  #49 = Utf8               ()Ljava/lang/String;
  #50 = Utf8               (Ljava/lang/String;)V
  #51 = Utf8               intern
  #52 = Utf8               java/lang/System
  #53 = Utf8               out
  #54 = Utf8               Ljava/io/PrintStream;
  #55 = Utf8               println
  #56 = Utf8               (Z)V
{
  public com.kiibos.micoservice.kiibos_8_jvm.stringIntern.StringTest01();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 9: 0

  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=3, locals=8, args_size=1
         0: ldc           #2                  // String baseStr
         2: astore_1
         3: ldc           #3                  // String baseStr01
         5: astore_3
         6: ldc           #3                  // String baseStr01
         8: astore        4
        10: new           #4                  // class java/lang/StringBuilder
        13: dup
        14: invokespecial #5                  // Method java/lang/StringBuilder."<init>":()V
        17: aload_1
        18: invokevirtual #6                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        21: ldc           #7                  // String 01
        23: invokevirtual #6                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        26: invokevirtual #8                  // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        29: astore        5
        31: ldc           #3                  // String baseStr01
        33: astore        6
        35: new           #9                  // class java/lang/String
        38: dup
        39: ldc           #3                  // String baseStr01
        41: invokespecial #10                 // Method java/lang/String."<init>":(Ljava/lang/String;)V
        44: invokevirtual #11                 // Method java/lang/String.intern:()Ljava/lang/String;
        47: astore        7
        49: getstatic     #12                 // Field java/lang/System.out:Ljava/io/PrintStream;
        52: aload_3
        53: aload         4
        55: if_acmpne     62
        58: iconst_1
        59: goto          63
        62: iconst_0
        63: invokevirtual #13                 // Method java/io/PrintStream.println:(Z)V
        66: getstatic     #12                 // Field java/lang/System.out:Ljava/io/PrintStream;
        69: aload_3
        70: aload         5
        72: if_acmpne     79
        75: iconst_1
        76: goto          80
        79: iconst_0
        80: invokevirtual #13                 // Method java/io/PrintStream.println:(Z)V
        83: getstatic     #12                 // Field java/lang/System.out:Ljava/io/PrintStream;
        86: aload_3
        87: aload         6
        89: if_acmpne     96
        92: iconst_1
        93: goto          97
        96: iconst_0
        97: invokevirtual #13                 // Method java/io/PrintStream.println:(Z)V
       100: getstatic     #12                 // Field java/lang/System.out:Ljava/io/PrintStream;
       103: aload_3
       104: aload         7
       106: if_acmpne     113
       109: iconst_1
       110: goto          114
       113: iconst_0
       114: invokevirtual #13                 // Method java/io/PrintStream.println:(Z)V
       117: return
      LineNumberTable:
        line 12: 0
        line 15: 3
        line 16: 6
        line 17: 10
        line 18: 31
        line 19: 35
        line 21: 49
        line 22: 66
        line 23: 83
        line 24: 100
        line 25: 117
      StackMapTable: number_of_entries = 8
        frame_type = 255 /* full_frame */
          offset_delta = 62
          locals = [ class "[Ljava/lang/String;", class java/lang/String, top, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String ]
          stack = [ class java/io/PrintStream ]
        frame_type = 255 /* full_frame */
          offset_delta = 0
          locals = [ class "[Ljava/lang/String;", class java/lang/String, top, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String ]
          stack = [ class java/io/PrintStream, int ]
        frame_type = 79 /* same_locals_1_stack_item */
          stack = [ class java/io/PrintStream ]
        frame_type = 255 /* full_frame */
          offset_delta = 0
          locals = [ class "[Ljava/lang/String;", class java/lang/String, top, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String ]
          stack = [ class java/io/PrintStream, int ]
        frame_type = 79 /* same_locals_1_stack_item */
          stack = [ class java/io/PrintStream ]
        frame_type = 255 /* full_frame */
          offset_delta = 0
          locals = [ class "[Ljava/lang/String;", class java/lang/String, top, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String ]
          stack = [ class java/io/PrintStream, int ]
        frame_type = 79 /* same_locals_1_stack_item */
          stack = [ class java/io/PrintStream ]
        frame_type = 255 /* full_frame */
          offset_delta = 0
          locals = [ class "[Ljava/lang/String;", class java/lang/String, top, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String, class java/lang/String ]
          stack = [ class java/io/PrintStream, int ]
}
SourceFile: "StringTest01.java"
